/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "ID3FzOZGGOHGbwOCbQCdzw",
        engine: "mysql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "Listings": a.model({
        idListings: a.integer().required(),
        Name: a.string()
    }).identifier([
        "idListings"
    ])
});
